### ISSUE TITLE
Missing dependency Blake3

### ISSUE THREAD

**Issue by mbliesnerzappos** [BishopFox/dufflebag#2]
100- % of customers impacted: [100]%
Engineers- Affected Users: [Engineers / Operators / Customers]
Low- Urgency: [High / Medium / Low]

There is a dependency missing for Blake3.  I'm new to go and have been unable to make it work.

Thanks for your help.

**Comment by dan-bishopfox** [comment]
Ahh, must have missed that. Thanks! 

Added the dependency in the new Readme. 73676730548ed29952d576ab367e0ccaee06826c
